name: ShopkeepersEI
version: '${pluginVersion}'
authors: [Reddishye]
website: '${pluginUrl}'
description: '${pluginDescription}'
main: es.redactado.shopkeepersEI.ShopkeepersEI
api-version: '1.20'
depend: [Shopkeepers]
softdepend: [ExecutableItems, SCore]
